# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6

    working_directory: ~/snake_case_yaml

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            # Both setup.py and requirements.txt install dependencies, but slightly different.
            - v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: check black
          command: |
            . .venv/bin/activate
            black --line-length 79 *.py snake_case_yaml tests --check

      - run:
          name: check isort
          command: |
            . .venv/bin/activate
            isort --recursive snake_case_yaml tests *.py --check-only

      - run:
          name: check flake8
          command: |
            . .venv/bin/activate
            flake8 --max-complexity 10 *.py snake_case_yaml tests

      - run:
          name: check pylint
          command: |
            . .venv/bin/activate
            pylint *.py snake_case_yaml tests --disable=fixme

      - run:
          name: pytest
          command: |
            . .venv/bin/activate
            python setup.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
